# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e886272bf598b2ca99ef7f043efac7a1257d08335e08cf2795365850f676683618cafc3f97135c184f0c2fbb107f7d78ab27170d0344caf154fba1289971de4c

test:
  secret_key_base: a8715564b2a6827d8bf021ede6f38c3f4500646c499a37c2d4a3ac42968661fa053ef01a5fffddeafe5b795ca159501f00b2599fff51e438fdd007384a6b21a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
